function(get_qt_version)
    file(READ "${VCPKG_OVERLAYS_DIR}/qt5-base/vcpkg.json" _QT_PORTFILE_CONTENTS)
    set(QT_SEMVER_REGEX " *\"version.*\": \"([0-9]+)\\.([0-9]+)\\.([0-9]+)\" *")
    string(REGEX MATCH ${QT_SEMVER_REGEX} QT_VERSIONS ${_QT_PORTFILE_CONTENTS})
    string(REGEX REPLACE ${QT_SEMVER_REGEX} "\\1" QT_VERSION_MAJOR ${QT_VERSIONS})
    string(REGEX REPLACE ${QT_SEMVER_REGEX} "\\2" QT_VERSION_MINOR ${QT_VERSIONS})
    string(REGEX REPLACE ${QT_SEMVER_REGEX} "\\3" QT_VERSION_PATCH ${QT_VERSIONS})

    set(QT_VERSION_MAJOR ${QT_VERSION_MAJOR} CACHE STRING "" FORCE)
    set(QT_VERSION_MINOR ${QT_VERSION_MINOR} CACHE STRING "" FORCE)
    set(QT_VERSION_PATCH ${QT_VERSION_PATCH} CACHE STRING "" FORCE)

    message(STATUS "Qt version: ${QT_VERSION_MAJOR}.${QT_VERSION_MINOR}.${QT_VERSION_PATCH} (from overlay port file)")
endfunction()


function(get_python_version)
    file(READ "${VCPKG_OVERLAYS_DIR}/python3/portfile.cmake" _PYTHON_PORTFILE_CONTENTS)
    string(REGEX MATCH "set *\\(PYTHON_VERSION_MAJOR *([0-9]+)\\)" PYTHON_VERSION_MAYOR ${_PYTHON_PORTFILE_CONTENTS})
    string(REGEX REPLACE "set *\\(PYTHON_VERSION_MAJOR *([0-9]+)\\)" "\\1" PYTHON_VERSION_MAYOR ${PYTHON_VERSION_MAYOR})

    string(REGEX MATCH "set *\\(PYTHON_VERSION_MINOR *([0-9]+)\\)" PYTHON_VERSION_MINOR ${_PYTHON_PORTFILE_CONTENTS})
    string(REGEX REPLACE "set *\\(PYTHON_VERSION_MINOR *([0-9]+)\\)" "\\1" PYTHON_VERSION_MINOR ${PYTHON_VERSION_MINOR})

    string(REGEX MATCH "set *\\(PYTHON_VERSION_PATCH *([0-9]+)\\)" PYTHON_VERSION_PATCH ${_PYTHON_PORTFILE_CONTENTS})
    string(REGEX REPLACE "set *\\(PYTHON_VERSION_PATCH *([0-9]+)\\)" "\\1" PYTHON_VERSION_PATCH ${PYTHON_VERSION_PATCH})

    set(PYTHON_VERSION_MAJOR ${PYTHON_VERSION_MAYOR} CACHE STRING "" FORCE)
    set(PYTHON_VERSION_MINOR ${PYTHON_VERSION_MINOR} CACHE STRING "" FORCE)
    set(PYTHON_VERSION_PATCH ${PYTHON_VERSION_PATCH} CACHE STRING "" FORCE)

    message(STATUS "Python version: ${PYTHON_VERSION_MAYOR}.${PYTHON_VERSION_MINOR}.${PYTHON_VERSION_PATCH} (from overlay port file)")
endfunction()


function(get_ffmpeg_version)
    file(READ "${PACKAGES_DIR}/vcpkg/ports/ffmpeg/vcpkg.json" _FFMPEG_PORTFILE_CONTENTS)
    set(FFMPEG_SEMVER_REGEX ".*\"version.*\": \"([0-9]+)\.([0-9]+)\.([0-9]+)\".*")
    string(REGEX MATCH ${FFMPEG_SEMVER_REGEX} FFMPEG_VERSIONS ${_FFMPEG_PORTFILE_CONTENTS})
    string(REGEX REPLACE ${FFMPEG_SEMVER_REGEX} "\\1" FFMPEG_VERSION_MAJOR ${FFMPEG_VERSIONS})
    string(REGEX REPLACE ${FFMPEG_SEMVER_REGEX} "\\2" FFMPEG_VERSION_MINOR ${FFMPEG_VERSIONS})
    string(REGEX REPLACE ${FFMPEG_SEMVER_REGEX} "\\3" FFMPEG_VERSION_PATCH ${FFMPEG_VERSIONS})

    set(FFMPEG_VERSION_MAJOR ${FFMPEG_VERSION_MAJOR} CACHE STRING "" FORCE)
    set(FFMPEG_VERSION_MINOR ${FFMPEG_VERSION_MINOR} CACHE STRING "" FORCE)
    set(FFMPEG_VERSION_PATCH ${FFMPEG_VERSION_PATCH} CACHE STRING "" FORCE)

    message(STATUS "FFMpeg version: ${FFMPEG_VERSION_MAJOR}.${FFMPEG_VERSION_MINOR}.${FFMPEG_VERSION_PATCH} (from overlay port file)")
endfunction()


function(get_oiio_version)
    file(READ "${VCPKG_OVERLAYS_DIR}/openimageio/vcpkg.json" _OIIO_PORTFILE_CONTENTS)
    set(OIIO_SEMVER_REGEX ".*\"version.*\": \"([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9]+)\".*")
    string(REGEX MATCH ${OIIO_SEMVER_REGEX} OIIO_VERSIONS ${_OIIO_PORTFILE_CONTENTS})
    string(REGEX REPLACE ${OIIO_SEMVER_REGEX} "\\1" OIIO_VERSION_MAJOR ${OIIO_VERSIONS})
    string(REGEX REPLACE ${OIIO_SEMVER_REGEX} "\\2" OIIO_VERSION_MINOR ${OIIO_VERSIONS})
    string(REGEX REPLACE ${OIIO_SEMVER_REGEX} "\\3" OIIO_VERSION_PATCH ${OIIO_VERSIONS})
    string(REGEX REPLACE ${OIIO_SEMVER_REGEX} "\\4" OIIO_VERSION_TWEAK ${OIIO_VERSIONS})

    set(OIIO_VERSION_MAJOR ${OIIO_VERSION_MAJOR} CACHE STRING "" FORCE)
    set(OIIO_VERSION_MINOR ${OIIO_VERSION_MINOR} CACHE STRING "" FORCE)
    set(OIIO_VERSION_PATCH ${OIIO_VERSION_PATCH} CACHE STRING "" FORCE)
    set(OIIO_VERSION_TWEAK ${OIIO_VERSION_TWEAK} CACHE STRING "" FORCE)

    message(STATUS "OpenImageIO version: ${OIIO_VERSION_MAJOR}.${OIIO_VERSION_MINOR}.${OIIO_VERSION_PATCH}.${OIIO_VERSION_TWEAK} (from overlay port file)")
endfunction()